default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: rob

development:
  <<: *default
  database: nerdbeers_dev

test:
  <<: *default
  database: nerdbeers_test
